In [3]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount("/content/drive")



Mounted at /content/drive


In [4]:
filepath="/content/drive/My Drive/MachineLearningUdemy/Section2/Data2.csv"
df = pd.read_csv(filepath)
df

PassengerId  Survived  Pclass  \
0              2         1       1   
1              4         1       1   
2              7         0       1   
3             11         1       3   
4             12         1       1   
..           ...       ...     ...   
178          872         1       1   
179          873         0       1   
180          880         1       1   
181          888         1       1   
182          890         1       1   

                                                  Name     Sex   Age  SibSp  \
0    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
1         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
2                              McCarthy, Mr. Timothy J    male  54.0      0   
3                      Sandstrom, Miss. Marguerite Rut  female   4.0      1   
4                             Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
178   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
179                           Carlsson, Mr. Frans Olof    male  33.0      0   
180      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
181                       Graham, Miss. Margaret Edith  female  19.0      0   
182                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
0        0  PC 17599  71.2833          C85        C  
1        0    113803  53.1000         C123        S  
2        0     17463  51.8625          E46        S  
3        1   PP 9549  16.7000           G6        S  
4        0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
178      1     11751  52.5542          D35        S  
179      0       695   5.0000  B51 B53 B55        S  
180      1     11767  83.1583          C50        C  
181      0    112053  30.0000          B42        S  
182      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [5]:
X=df.drop(["Survived"], axis=1)
X=X.values
print(X)

Y= df["Survived"].values
print(Y)

[[2 1 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)' ... 71.2833
  'C85' 'C']
 [4 1 'Futrelle, Mrs. Jacques Heath (Lily May Peel)' ... 53.1 'C123' 'S']
 [7 1 'McCarthy, Mr. Timothy J' ... 51.8625 'E46' 'S']
 ...
 [880 1 'Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)' ... 83.1583 'C50'
  'C']
 [888 1 'Graham, Miss. Margaret Edith' ... 30.0 'B42' 'S']
 [890 1 'Behr, Mr. Karl Howell' ... 30.0 'C148' 'C']]
[1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 1 1
 1 1 1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1
 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1
 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 1 1 1 1
 0 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1]


In [7]:
def is_numeric(element):
    try:
        float(element)
        return True
    except ValueError:
        return False

numeric_mask = np.vectorize(is_numeric)(X[0])
non_numeric_indices = np.where(~numeric_mask)[0]
non_numeric_indices


array([ 2,  3,  7,  9, 10])

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct= ColumnTransformer(transformers =[("encoder", OneHotEncoder(), non_numeric_indices)], remainder="passthrough")
XCopy= np.array(ct.fit_transform(X))
XCopy

NameError: name 'non_numeric_indices' is not defined

In [37]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(Y)
y

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1])

We will do it once again but without the formation of X and Y. We will do all operations directly on the dataframes. And we will speifically identify whoch ones could be categorical features and not just encode all string features.

In [39]:
df = pd.read_csv(filepath)
df.head()

PassengerId  Survived  Pclass  \
0            2         1       1   
1            4         1       1   
2            7         0       1   
3           11         1       3   
4           12         1       1   

                                                Name     Sex   Age  SibSp  \
0  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
2                            McCarthy, Mr. Timothy J    male  54.0      0   
3                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
4                           Bonnell, Miss. Elizabeth  female  58.0      0   

   Parch    Ticket     Fare Cabin Embarked  
0      0  PC 17599  71.2833   C85        C  
1      0    113803  53.1000  C123        S  
2      0     17463  51.8625   E46        S  
3      1   PP 9549  16.7000    G6        S  
4      0    113783  26.5500  C103        S

In [40]:
uniqueVals = df.nunique()
uniqueVals

PassengerId    183
Survived         2
Pclass           3
Name           183
Sex              2
Age             63
SibSp            4
Parch            4
Ticket         127
Fare            93
Cabin          133
Embarked         3
dtype: int64

In [9]:
encoding_columns=["Sex", "SibSp", "Parch", "Embarked", "Pclass"]
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct= ColumnTransformer(transformers =[("encoder", OneHotEncoder(), encoding_columns)], remainder="passthrough")
XCopy= np.array(ct.fit_transform(df))
XCopy

array([[1.0, 0.0, 0.0, ..., 'PC 17599', 71.2833, 'C85'],
       [1.0, 0.0, 0.0, ..., '113803', 53.1, 'C123'],
       [0.0, 1.0, 1.0, ..., '17463', 51.8625, 'E46'],
       ...,
       [1.0, 0.0, 1.0, ..., '11767', 83.1583, 'C50'],
       [1.0, 0.0, 1.0, ..., '112053', 30.0, 'B42'],
       [0.0, 1.0, 1.0, ..., '111369', 30.0, 'C148']], dtype=object)

In [3]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount("/content/drive")
filepath="/content/drive/My Drive/MachineLearningUdemy/Section2/Data4.csv"


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
df =pd.read_csv(filepath)
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [6]:
from sklearn.preprocessing import StandardScaler

sc= StandardScaler()

features = df.drop(["quality"], axis=1)
target = df["quality"]


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2,random_state=42 )
X_train.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
493            8.7             0.690         0.31             3.0      0.086   
354            6.1             0.210         0.40             1.4      0.066   
342           10.9             0.390         0.47             1.8      0.118   
834            8.8             0.685         0.26             1.6      0.088   
705            8.4             1.035         0.15             6.0      0.073   

     free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
493                 23.0                  81.0  1.00020  3.48       0.74   
354                 40.5                 165.0  0.99120  3.25       0.59   
342                  6.0                  14.0  0.99820  3.30       0.75   
834                 16.0                  23.0  0.99694  3.32       0.47   
705                 11.0                  54.0  0.99900  3.37       0.49   

     alcohol  
493     11.6  
354     11.9  
342      9.8  
834      9.4  
705      9.9

In [12]:
X_train = sc.fit_transform(X_train)
X_train=pd.DataFrame(X_train)
X_train

X_test = sc.transform(X_test)
X_test= pd.DataFrame(X_test)
X_test

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


0      1             2     3      4     5      6        7     8     9   \
0     7.7  0.560  8.000000e-02  2.50  0.114  14.0   46.0  0.99710  3.24  0.66   
1     7.8  0.500  1.700000e-01  1.60  0.082  21.0  102.0  0.99600  3.39  0.48   
2    10.7  0.670  2.200000e-01  2.70  0.107  17.0   34.0  1.00040  3.28  0.98   
3     8.5  0.460  3.100000e-01  2.25  0.078  32.0   58.0  0.99800  3.33  0.54   
4     6.7  0.460  2.400000e-01  1.70  0.077  18.0   34.0  0.99480  3.39  0.60   
..    ...    ...           ...   ...    ...   ...    ...      ...   ...   ...   
315   6.8  0.640  2.222182e-17  2.70  0.123  15.0   33.0  0.99538  3.44  0.63   
316   6.6  0.630  2.222182e-17  4.30  0.093  51.0   77.5  0.99558  3.20  0.45   
317   8.3  0.600  2.500000e-01  2.20  0.118   9.0   38.0  0.99616  3.15  0.53   
318   8.8  0.270  3.900000e-01  2.00  0.100  20.0   27.0  0.99546  3.15  0.69   
319   9.1  0.765  4.000000e-02  1.60  0.078   4.0   14.0  0.99800  3.29  0.54   

       10  
0     9.6  
1     9.5  
2     9.9  
3     9.8  
4    10.6  
..    ...  
315  11.3  
316   9.5  
317   9.8  
318  11.2  
319   9.7  

[320 rows x 11 columns]