In [ ]:
import numpy as np
import pandas as pd

### Create an empty and full numpy array

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array([])
arr

array([], dtype=float64)

### Create a numpy array of zeros and ones

In [ ]:
arr = np.ones(25)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.zeros(25)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

### Write a code to check if a row exists in a np array

In [ ]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
print([1,2,3,4] in arr.tolist())

True


In [ ]:
arr = np.array([["a", "b", "c", "d"], [1,2,3,4]])
arr

array([['a', 'b', 'c', 'd'],
       ['1', '2', '3', '4']], dtype='<U21')

### Find rows that contain non-numeric values in the np array

In [ ]:
import numpy as np
arr1 = np.array([np.arange(50,74,3), np.arange(80,104,3), np.arange(110, 134,3)])
arr1

array([[ 50,  56,  62,  68],
       [ 80,  86,  92,  98],
       [110, 116, 122, 128]])

In [ ]:
arr0 =np.array([np.zeros(8), np.zeros(8), np.zeros(8)])
arr0

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arrI = np.array([])

### Code to replace particular indices in an numpy array that do not satisfy a condition

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.array([1,33,45,23,20,15,71,81,100])
arr

array([  1,  33,  45,  23,  20,  15,  71,  81, 100])

In [3]:
arr[arr>50]=22
arr

array([ 1, 33, 45, 23, 20, 15, 22, 22, 22])

### Code to find indices that satisfy a condition

In [7]:
arr = np.array([12,32,24,55,91,92,39,133])
arr2 = np.where(arr>50);
arr2

(array([3, 4, 5, 7]),)

### Code to replace all negative values with zeros

In [8]:
arr = np.array([-1,-11,12,-31,10,11,121,322,-100,345,542])
arr[arr<0]=0
arr

array([  0,   0,  12,   0,  10,  11, 121, 322,   0, 345, 542])

### Code to replace all NaN values with mean of columns

In [10]:
arr = np.array([[1,12,13,31],[4,54,61,13], [np.nan, 12, np.nan,30],[14,15,16,17]])
arr

array([[ 1., 12., 13., 31.],
       [ 4., 54., 61., 13.],
       [nan, 12., nan, 30.],
       [14., 15., 16., 17.]])

In [17]:
col_mean = np.nanmean(arr, axis=0)
col_mean

array([ 6.33333333, 23.25      , 30.        , 22.75      ])

In [18]:
inds = np.where(np.isnan(arr))
inds

(array([2, 2]), array([0, 2]))

In [19]:
arr[inds]= np.take(col_mean, inds[1])
arr

array([[ 1.        , 12.        , 13.        , 31.        ],
       [ 4.        , 54.        , 61.        , 13.        ],
       [ 6.33333333, 12.        , 30.        , 30.        ],
       [14.        , 15.        , 16.        , 17.        ]])

### Write a piece of code to replace certain positions in a numpy array with other elements stored in a different array

In [20]:
arr1 = np.array([12,13,14,15,16,17,71,61,51,41])
arr2 = np.array([23,43,54,46])
arr1.put([0,1,2], arr2)
arr1

array([23, 43, 54, 15, 16, 17, 71, 61, 51, 41])

In [21]:
arr1 = np.array([[101,102,103,104,105], [106,107,108,109,110], [111,112,113,114,115],[116,117,118,119,120]])
arr2 = np.zeros(5)
arr1.put([0,5,10,15], arr2)
arr1

array([[  0, 102, 103, 104, 105],
       [  0, 107, 108, 109, 110],
       [  0, 112, 113, 114, 115],
       [  0, 117, 118, 119, 120]])

In [23]:
arr1 = np.array([102,103,104,105,106,107])
arr2 = np.zeros(3)
arr1.put([0,3,13], arr2, mode="clip")
arr1

array([  0, 103, 104,   0, 106,   0])

### Code to find all positions at which the value is equal to 0.

In [24]:
arr1 = np.array([0,0,12,31,34,43,54,65,0,9,0])
arr2 = np.where(arr1==0)
arr2

(array([ 0,  1,  8, 10]),)

In [26]:
arr1 = np.array([[12,0,0,13],[14,0,0,15],[12,0,0,44],[32,0,0,34]])
arr2 = (arr1==0)
arr2

array([[False,  True,  True, False],
       [False,  True,  True, False],
       [False,  True,  True, False],
       [False,  True,  True, False]])

### Code to remove all non-numeric value containing columns in a matrix.

In [27]:
arr1 = np.array([[552,342,100, np.nan],[555,567,987,43],[3456,431,432,235],[101,102,np.nan, 103]])
arr1

array([[ 552.,  342.,  100.,   nan],
       [ 555.,  567.,  987.,   43.],
       [3456.,  431.,  432.,  235.],
       [ 101.,  102.,   nan,  103.]])

In [34]:
arr2=arr1[:,~np.isnan(arr1).any(axis=0)]
arr2

array([[ 552.,  342.],
       [ 555.,  567.],
       [3456.,  431.],
       [ 101.,  102.]])

### Code to return indices of arrays containing element larger than X

In [35]:
arr3 = np.array([[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24],[31,32,33,34,35],[36,37,38,39,40],[1,2,3,4,5]])
arr3

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [ 1,  2,  3,  4,  5]])

In [38]:
arr4 = np.where(np.any(arr3>15, axis=1))
arr4

(array([1, 2, 3, 4]),)

### Code to find if any specific elements of a list exist in a numpy array

In [41]:
import numpy as np
arr = np.array([1,2,3,4,5,19,12,13,14, 223, 224,15])
arr1=[4,3,5, 224,223]
arr2 = np.isin(arr, arr1)
arr2

array([False, False,  True,  True,  True, False, False, False, False,
        True,  True, False])

### Write Code to combine two arrays index by index.

In [44]:
arr = np.array([1,2,3,4,5])
arr1 =np.array([12,13,14,15,16])
arr2 = np.dstack([arr, arr1])
arr2

array([[[ 1, 12],
        [ 2, 13],
        [ 3, 14],
        [ 4, 15],
        [ 5, 16]]])

### Write a code to sort a numpy array

In [45]:
arr1 = np.array([12,10,-1,-33,100,103])
ans =np.sort(arr1)
ans

array([-33,  -1,  10,  12, 100, 103])

### Write a code that returns an array of indices of sorted array elements in an array

In [46]:
arr1 = np.array([13,14,51,23,-11,23,32])
arr2 = np.argsort(arr1)
arr2

array([4, 0, 1, 3, 5, 6, 2])

### Write a code to find the k smallest values in a numpy array

In [47]:
arr1=np.array([-22,-32,-2,22,34,45,10,102,103,104,55,45])
arr2 = np.sort(arr1)
arr3 = arr2[:4]
arr3

array([-32, -22,  -2,  10])

### Write a code to find the nth largest values in a numpy array

In [48]:
arr1 = np.array([22,-32,-42,33,31,98,76]);
arr2 = np.sort(arr1)
arr3 = np.flip(arr2)
ans = arr3[2]
print("Third largest element:\t")
ans


Third largest element:	


33

### Write a piece of code to sort the values in a matrix

In [54]:
arr1 = np.array([[12,-33,-45,102,103,104],[14,15,82,34,4,0],[4,5,23,31,-11,-124],[-99,99,100,1333,-23,32]])
shap= arr1.shape
row = shap[0]
col=shap[1]
row

4

In [55]:
arr2 = arr1.flatten()
arr2

array([  12,  -33,  -45,  102,  103,  104,   14,   15,   82,   34,    4,
          0,    4,    5,   23,   31,  -11, -124,  -99,   99,  100, 1333,
        -23,   32])

In [56]:
arr3 = np.sort(arr2)
arr4 = arr3.reshape(shap)
arr4

array([[-124,  -99,  -45,  -33,  -23,  -11],
       [   0,    4,    4,    5,   12,   14],
       [  15,   23,   31,   32,   34,   82],
       [  99,  100,  102,  103,  104, 1333]])

### Write a piece of code to filter out the integer values from a numpy array that contains float values

In [59]:
arr1 = np.array([1.5, 2.3, 3.7, 4.1, 5.0,1])

arr2 = arr1 [arr1!= arr1.astype(int)]
arr2

array([1.5, 2.3, 3.7, 4.1])

### Write a piece of code to make a numpy array with random values

In [62]:
arr = np.random.randint(100, size=20)
arr

array([43,  1, 54,  7, 37, 49, 48, 53, 86, 75,  0, 86, 86, 26, 88, 20, 88,
       83, 37, 22])